{% set name = "tacco" %}
{% set version = "0.4.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tacco-{{ version }}.tar.gz
  sha256: b64a3a056bc36102c189de5108ccb55f33f35e292250da106dcb2d5817e4495d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - joblib
    - numba >=0.51.2
    - numpy
    - matplotlib-base !=3.7
    - seaborn
    - sparse_dot_mkl >=0.7.3
    - scanpy >=1.7.0
    - statsmodels
    - anndata >=0.9.0
    - pandas >=1.1.0
    - scipy >=1.6.0
    - mkl
    - mkl-service
    - scikit-learn
    - threadpoolctl
    - pyamg

test:
  imports:
    - tacco
  source_files:
    - tests/
  commands:
    - pytest -k "not test_benchmark_annotate"
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/simonwm/tacco
  summary: 'TACCO: Transfer of Annotations to Cells and their COmbinations'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENCE.txt
    - NOTICE.md
  doc_url: https://simonwm.github.io/tacco
  dev_url: https://github.com/simonwm/tacco

extra:
  recipe-maintainers:
    - simonwm
    - JWatter
